### ISSUE TITLE
PrintScreen takes screenshots only in BASIC Engine NG

### ISSUE THREAD

**Issue by CityAceE** [uli/basicengine-firmware#111]
Is it correct or it's a bug?

RX and LT just print "W" symbol instead of taking a screenshot.

**Comment by uli** [comment]
That is supposed to work. I just tried in on desktop Linux, and it didn't work because the DE intercepts the PrintScreen key. I fixed that by grabbing the keyboard in fullscreen mode, and then taking screenshots works just fine. But that's not the issue on the embedded platforms.

I looked at the SDL key scancodes, and there is SDL_SCANCODE_PRINTSCREEN and SDL_SCANCODE_SYSREQ, even though these are the same keys on my keyboard. In the Linux DE the scancode produced is SDL_SCANCODE_PRINTSCREEN, which is the same as the USB scancode for that key, so that makes sense. I suspect that when using the KMSDRM driver, the scancode produced is SDL_SCANCODE_SYSREQ, which happens to be SDL_SCANCODE_W + 0x80...
