### ISSUE TITLE
SDL build fails to load sound font

### ISSUE THREAD

**Issue by bitartrate** [uli/basicengine-firmware#40]
Originally I thought sound was not really working at all.  But I know have discovered to get sound working 1mgm.sf2 must be in the same directory as the program that uses it.

**Comment by uli** [comment]
The SDL build reads the sound font from the current directory, unless the environment variable ENGINEBASIC_ROOT specifies a different (absolute) path. The reason is that I'm not quite sure what an appropriate directory structure would look like, since the SDL build can run on pretty much anything.

(My motivation for making that port in the first place is to make an Antix Linux Live CD that can be used to boot into Engine BASIC on old (ca. 1998 and up) PCs.)

I guess a reasonable solution would be to have a command-line parameter for setting the root directory, and to default to the cwd if none is specified.

**Comment by bitartrate** [comment]
After I realized that it looks in the CWD it became clear why and I do like that functionality.  I am not sure I would recommend anything different at the moment.  Maybe in time after I make a dedicated Linux install a workflow will emerge.  I REALLY like that you made an SDL version.  I have run it in full screen and it is really great.

**Comment by uli** [comment]
The SDL build now defaults to CWD as root, and there is also the "-r" command line option, so this should not be an issue anymore.
